routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile', 'ProfileController@index')->name('profile');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::post('/profile', 'ProfileController@update');

Route::resource('/users', 'UserController')->middleware('auth');
Route::resource('/messages', 'MessageController')->middleware('auth');
Route::middleware('auth')->get('/users/{user}/messages', 'UserController@messages')->name('users.messages');

Route::post('/avatar', 'AvatarController@upload');

app/Message.php
<?php

namespace TwitterLite;

use Illuminate\Database\Eloquent\Model;

/** Message posted by users */
class Message extends Model
{

    protected $fillable = [ 'content' ];

    /** Get the message author */
    public function user()
    {
        return $this->belongsTo('TwitterLite\User');
    }
}

app/Http/Controllers/API/MessageController.php
<?php

namespace TwitterLite\Http\Controllers\API;

use TwitterLite\Message;
USE TwitterLite\Http\Resources\MessageResource;
use Illuminate\Http\Request;
use TwitterLite\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\Access\AuthorizationException;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return MessageResource::collection(Message::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request 
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $message = Auth::user()->messages()->create($request->input());
        return new MessageResource($message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        return new MessageResource($message);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        if ($message->user != Auth::user()) {
            throw new AuthorizationException();
        }
        $message->update($request->input());
        return new MessageResource($message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        if ($message->user != Auth::user()) {
            throw new AuthorizationException();
        }
        $message->delete();
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace TwitterLite\Http\Controllers;

use TwitterLite\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\Access\AuthorizationException;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = Message::orderBy('created_at', 'desc')->paginate(15);

        return view('messages.index', ['messages' => $messages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'content' => 'required|max:300',
        ]);

        $message = Auth::user()->messages()->create([
            "content" => $request->input('content')
        ]);

        return redirect()->route('messages.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        if ($message->user != Auth::user()) {
            throw new AuthorizationException();
        }

        return view('messages.edit', ['message' => $message]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        if ($message->user != Auth::user()) {
            throw new AuthorizationException();
        }

        $request->validate([
            'content' => 'required|max:300',
        ]);

        $message->content = $request->input('content');

        $message->save();
    
        return redirect()->route('messages.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \TwitterLite\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        if ($message->user != Auth::user()) {
            throw new AuthorizationException();
        }

        $message->delete();

        return redirect()->route('messages.index');
    }
}

resources/views/messages/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                <h3>Poster un message</h3>
                <br/>
                <a href="{{ route('home') }}" class="btn btn-info">← Retour</a>
                <br/>
                <br/>
                <form method="POST" action="/messages">
                    @csrf
                    <textarea class="form-control @error('content') is-invalid @enderror" 
                        name="content" 
                        cols="80" rows="10"
                        minlength="1" maxlength="300" 
                        required 
                        placeholder="Qu'es-tu en train de faire en ce moment?"
                    ></textarea>
                    <br/>
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                </form>
                </div>
            </div>
        </div>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
</div>
@endsection

resources/views/messages/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h3>Éditer le message</h3>
                    <br />
                    <a href="{{ route('messages.index') }}" class="btn btn-info">← Retour</a>
                    <br />
                    <br />
                    <form method="POST" action="{{ route('messages.update', $message) }}">
                        @method('PUT')
                        @csrf
                        <textarea class="form-control @error('content') is-invalid @enderror" name="content" cols="80"
                            rows="10" minlength="1" maxlength="300" required>{{ $message->content }}</textarea>
                        <br />

                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br />
                        @endif

                        <button type="submit" class="btn btn-primary">Sauvegarder</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/messages/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="media">
                        <div class="media">
                            @if (Auth::user()->profile_picture)
                            <img src="{{ Auth::user()->profile_picture }}" class="profile-picture mr-3">
                            @else
                            <img src="/img/profile.jpg" class="profile-picture mr-3">
                            @endif
                            <div class="media-body message">
                                <a class="js-user-profile-link js-nav" href="{{ route('profile') }}">
                                    <h5 class="mt-0"><b>{{ Auth::user()->name }}</b></h5>
                                </a>
                                <h5 class="mt-0"><b>ID :</b> {{ Auth::user()->id }}</h5>
                                <h5 class="mt-0"><b>Inscit le :</b> {{ Auth::user()->created_at }}</h5>
                            </div>
                        </div>
                    </div>
                    <h5 class="mt-0"><b>Bio :</b> {{ Auth::user()->bio }}</h5>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h3>Liste des messages</h3>
                    <br />
                    <a href="{{ route('home') }}" class="btn btn-info">← Retour</a>
                    <br />
                    <br />
                    <form method="POST" action="/messages">
                        @csrf
                        <textarea class="form-control @error('content') is-invalid @enderror" name="content" size="80"
                            minlength="1" maxlength="300" required
                            placeholder="Qu'es-tu en train de faire en ce moment?"></textarea>
                        <br />
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </form>
                    <br />
                    @include('messages.list')
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/messages/list.blade.php
@if ($messages->count() == 0)
<div class="shadow-none p-3 mb-5 bg-light rounded">
<h4>Aucun message, c'est le début d'une grande aventure !</h4>
<br />
<pre>
          /\
         /**\
        /****\   /\
       /      \ /**\
      /  /\    /    \        /\    /\  /\      /\            /\/\/\  /\
     /  /  \  /      \      /  \/\/  \/  \  /\/  \/\  /\  /\/ / /  \/  \
    /  /    \/ /\     \    /    \ \  /    \/ /   /  \/  \/  \  /    \   \
   /  /      \/  \/\   \  /      \    /   /    \
__/__/_______/___/__\___\__________________________________________________<pre/>
</div>
@else
<ul class="list-group">
    @foreach ($messages as $message)
    <div class="shadow-none p-3 mb-5 bg-light rounded">
        <div class="media">
            <a class="js-user-profile-link js-nav" href="{{ route('users.show', $message->user) }}">
                @if ($message->user->profile_picture)
                <img src="{{ $message->user->profile_picture }}" class="profile-picture mr-3">
                @else
                <img src="/img/profile.jpg" class="profile-picture mr-3">
                @endif
            </a>
            <div class="media-body message">
                <a class="js-user-profile-link js-nav"  
                    href="{{ route('users.show', $message->user) }}">
                    <h5 class="mt-0"><b>{{ $message->user->name }}</b></h5>
                </a>
                <div class="float-right">
                    <div class="p-2 bd-highlight">
                        <h6><i>{{ $message->created_at }}</i>
                            @if ($message->created_at != $message->updated_at)
                            <br /><i>Édité à : {{ $message->updated_at }}</i>
                            @endif
                    </div>
                </div>
                </h6>
                <div class="message-content">{{ $message->content }}</div>
            </div>
        </div>
        <br />
        @if ($message->user == Auth::user())
        <div class="btn-group" role="group">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#exampleModal">
                    Supprimer
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <form method="POST" action="{{ route('messages.destroy', $message) }}">
                                @method('DELETE')
                                @csrf
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Supprimer Le message ?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            <a href="{{ route('messages.edit', $message) }}" class="btn btn-sm btn-info">Editer</a>
        </div>
        @endif
    </div>
    @endforeach
</ul>
{{ $messages->links() }}
@endif